language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: 0.7
    - julia: 1.0
    - julia: nightly

branches:
  only:
    - master

notifications:
  email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'VERSION >= v"0.7" && using Pkg; Pkg.clone(pwd()); Pkg.build("NLSProblems"); Pkg.test("NLSProblems"; coverage=true)'

after_success:
  - julia -e 'VERSION >= v"0.7" && using Pkg; cd(Pkg.dir("NLSProblems")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
