language: julia

os:
  - linux
  - osx
  - windows
  - freebsd

julia:
  - 1.3
  - 1
  - nightly

matrix:
  allow_failures:
    - julia: nightly

branches:
  only:
    - master

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; cd(Pkg.dir("NLSProblems")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
